version = 5.5.0
archive_dir = /etc/letsencrypt/archive/bettsfoundations.org
cert = /etc/letsencrypt/live/bettsfoundations.org/cert.pem
privkey = /etc/letsencrypt/live/bettsfoundations.org/privkey.pem
chain = /etc/letsencrypt/live/bettsfoundations.org/chain.pem
fullchain = /etc/letsencrypt/live/bettsfoundations.org/fullchain.pem
[renewalparams]
account = c16b6c29e032382c7524ad035e7f95f5
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
bettsfoundations.org = /var/www/certbot
www.bettsfoundations.org = /var/www/certbot
